-- Sustained perf users. Every account uses the same benchmark password: benchmark
-- The benchmark runner delivers across this whole recipient set and verifies cumulative mailbox counts.
INSERT INTO users (email, password, uid, gid, home, mail_location, active) VALUES
    ('user01@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user01', 'mdbox:/var/mail/vhosts/example.com/user01', true),
    ('user02@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user02', 'mdbox:/var/mail/vhosts/example.com/user02', true),
    ('user03@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user03', 'mdbox:/var/mail/vhosts/example.com/user03', true),
    ('user04@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user04', 'mdbox:/var/mail/vhosts/example.com/user04', true),
    ('user05@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user05', 'mdbox:/var/mail/vhosts/example.com/user05', true),
    ('user06@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user06', 'mdbox:/var/mail/vhosts/example.com/user06', true),
    ('user07@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user07', 'mdbox:/var/mail/vhosts/example.com/user07', true),
    ('user08@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user08', 'mdbox:/var/mail/vhosts/example.com/user08', true),
    ('user09@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user09', 'mdbox:/var/mail/vhosts/example.com/user09', true),
    ('user10@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user10', 'mdbox:/var/mail/vhosts/example.com/user10', true),
    ('user11@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user11', 'mdbox:/var/mail/vhosts/example.com/user11', true),
    ('user12@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user12', 'mdbox:/var/mail/vhosts/example.com/user12', true),
    ('user13@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user13', 'mdbox:/var/mail/vhosts/example.com/user13', true),
    ('user14@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user14', 'mdbox:/var/mail/vhosts/example.com/user14', true),
    ('user15@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user15', 'mdbox:/var/mail/vhosts/example.com/user15', true),
    ('user16@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user16', 'mdbox:/var/mail/vhosts/example.com/user16', true),
    ('user17@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user17', 'mdbox:/var/mail/vhosts/example.com/user17', true),
    ('user18@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user18', 'mdbox:/var/mail/vhosts/example.com/user18', true),
    ('user19@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user19', 'mdbox:/var/mail/vhosts/example.com/user19', true),
    ('user20@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user20', 'mdbox:/var/mail/vhosts/example.com/user20', true),
    ('user21@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user21', 'mdbox:/var/mail/vhosts/example.com/user21', true),
    ('user22@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user22', 'mdbox:/var/mail/vhosts/example.com/user22', true),
    ('user23@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user23', 'mdbox:/var/mail/vhosts/example.com/user23', true),
    ('user24@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user24', 'mdbox:/var/mail/vhosts/example.com/user24', true),
    ('user25@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user25', 'mdbox:/var/mail/vhosts/example.com/user25', true),
    ('user26@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user26', 'mdbox:/var/mail/vhosts/example.com/user26', true),
    ('user27@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user27', 'mdbox:/var/mail/vhosts/example.com/user27', true),
    ('user28@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user28', 'mdbox:/var/mail/vhosts/example.com/user28', true),
    ('user29@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user29', 'mdbox:/var/mail/vhosts/example.com/user29', true),
    ('user30@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user30', 'mdbox:/var/mail/vhosts/example.com/user30', true),
    ('user31@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user31', 'mdbox:/var/mail/vhosts/example.com/user31', true),
    ('user32@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user32', 'mdbox:/var/mail/vhosts/example.com/user32', true),
    ('user33@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user33', 'mdbox:/var/mail/vhosts/example.com/user33', true),
    ('user34@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user34', 'mdbox:/var/mail/vhosts/example.com/user34', true),
    ('user35@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user35', 'mdbox:/var/mail/vhosts/example.com/user35', true),
    ('user36@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user36', 'mdbox:/var/mail/vhosts/example.com/user36', true),
    ('user37@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user37', 'mdbox:/var/mail/vhosts/example.com/user37', true),
    ('user38@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user38', 'mdbox:/var/mail/vhosts/example.com/user38', true),
    ('user39@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user39', 'mdbox:/var/mail/vhosts/example.com/user39', true),
    ('user40@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user40', 'mdbox:/var/mail/vhosts/example.com/user40', true),
    ('user41@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user41', 'mdbox:/var/mail/vhosts/example.com/user41', true),
    ('user42@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user42', 'mdbox:/var/mail/vhosts/example.com/user42', true),
    ('user43@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user43', 'mdbox:/var/mail/vhosts/example.com/user43', true),
    ('user44@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user44', 'mdbox:/var/mail/vhosts/example.com/user44', true),
    ('user45@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user45', 'mdbox:/var/mail/vhosts/example.com/user45', true),
    ('user46@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user46', 'mdbox:/var/mail/vhosts/example.com/user46', true),
    ('user47@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user47', 'mdbox:/var/mail/vhosts/example.com/user47', true),
    ('user48@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user48', 'mdbox:/var/mail/vhosts/example.com/user48', true),
    ('user49@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user49', 'mdbox:/var/mail/vhosts/example.com/user49', true),
    ('user50@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user50', 'mdbox:/var/mail/vhosts/example.com/user50', true),
    ('user51@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user51', 'mdbox:/var/mail/vhosts/example.com/user51', true),
    ('user52@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user52', 'mdbox:/var/mail/vhosts/example.com/user52', true),
    ('user53@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user53', 'mdbox:/var/mail/vhosts/example.com/user53', true),
    ('user54@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user54', 'mdbox:/var/mail/vhosts/example.com/user54', true),
    ('user55@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user55', 'mdbox:/var/mail/vhosts/example.com/user55', true),
    ('user56@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user56', 'mdbox:/var/mail/vhosts/example.com/user56', true),
    ('user57@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user57', 'mdbox:/var/mail/vhosts/example.com/user57', true),
    ('user58@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user58', 'mdbox:/var/mail/vhosts/example.com/user58', true),
    ('user59@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user59', 'mdbox:/var/mail/vhosts/example.com/user59', true),
    ('user60@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user60', 'mdbox:/var/mail/vhosts/example.com/user60', true),
    ('user61@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user61', 'mdbox:/var/mail/vhosts/example.com/user61', true),
    ('user62@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user62', 'mdbox:/var/mail/vhosts/example.com/user62', true),
    ('user63@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user63', 'mdbox:/var/mail/vhosts/example.com/user63', true),
    ('user64@example.com', '{PLAIN}benchmark', 5000, 5000, '/var/mail/vhosts/example.com/user64', 'mdbox:/var/mail/vhosts/example.com/user64', true)
ON CONFLICT (email) DO NOTHING;

-- Test aliases
INSERT INTO aliases (source, destination, active) VALUES
    ('admin@example.com', 'user01@example.com', true),
    ('postmaster@example.com', 'user01@example.com', true)
ON CONFLICT (source, destination) DO NOTHING;
